### ISSUE TITLE
COLMAP step not working in Docker build

### ISSUE THREAD

**Issue by Fabulani** [nbieck/HoldMyNeRF#2]
Inside Docker containers, the app crashes at the camera pose estimation stage with the following error:

`no transforms.json detected`

This is likely due to COLMAP crashing or not starting.

**Comment by Fabulani** [comment]
When submitting one of the examples, the following new error occurs:

```
==============================================================================
Feature extraction
==============================================================================

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 427, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/app/app.py", line 131, in run_nerf
    with open(os.path.join(tempdir, "transforms.json"), "r") as transforms:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp5dg4vjxy/transforms.json'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 427, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/app/app.py", line 161, in create_video_defaults
    return create_video(params)
  File "/app/app.py", line 164, in create_video
    checkpoint_file = [f.name for f in params[nerf_files] if f.name.endswith(".ingp")][0]
TypeError: 'NoneType' object is not iterable
```
